background {
    path = /home/corpxe/Pictures/wallpapers/main.jpg

    blur_passes = 4
    blur_size = 8
}

input-field {
    size = 260, 54

    outline_thickness = 2

    outer_color = rgba(122,162,247,0.5)
    inner_color = rgba(17,17,27,0.9)

    font_color = rgb(220,220,220)

    fade_on_empty = false

    rounding = 14

    placeholder_text = Password...
}
